title = "Easy"
body = '''
Engineering space-ready devices is a challenge, even for teams with
experience in the field.

Sometimes a great idea is not enough, and a project will stall at
the planning stage.

Space Cubics, Inc. provides comprehensive support for space
engineers, empowering teams to confidently enter the space
industry.
'''
