title = "もっと手軽に"
body = '''
<p>たとえ優れた技術があったとしても、宇宙開発の経験がない企業・団体にとって宇宙開発は簡単なものではありません。</p>

<p>宇宙開発に興味はあっても、どこから手を付けて良いのか分からず、企画段階で頓挫してしまうケースが多く見受けられます。</p>

<p>株式会社 Space Cubicsは、宇宙に興味のある企業・団体が手軽に宇宙開発に参入できるように宇宙開発のトータルサポートを提供します。</p>
'''
