title = "誰でも宇宙へ"
body = '''
Space Cubicsは低価格な宇宙用の機器とトータルサポートを提供することで、宇宙開発への参入を手軽にし、日本はもとよりアジアを中心とした民間の宇宙産業発展に貢献します。

多くの企業や団体そして個人までもが宇宙開発に参入することにより、宇宙に対するニーズが飛躍的に拡大して新たな産業が生まれ育っていくこと、それが Space Cubicsの設立目的です。

そしていつの日か、月にホテルが建ち、誰でも宇宙に行ける時代の実現を目指します。
'''
