title = "To Space"
body = '''
Space Cubics, Inc. provides affordable astrocomputing boards along
with comprehensive support. This supports the private space industry
in Japan and abroad.

Our boards enable large organizations, small companies, and even
individuals to participate in the growing space industry. This is our
core mission.

Maybe one day we will even take vacations on the moon.
'''
