name: Visual Regression Test

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      vrt_failed: ${{ steps.vrt-test.outcome == 'failure' }}
    env:
      ZOLA_VERSION: "0.21.0"
      ZOLA_BIN: ${{ github.workspace }}/zola
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Zola ${{ env.ZOLA_VERSION }}
        run: |
          curl -sL "https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz" | tar -xz
          $ZOLA_BIN --version

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Playwright test runner
        working-directory: test
        run: |
          npm install
          npm ls

      - name: Install Playwright browser modules and dependecies
        working-directory: test
        run: npx playwright install --with-deps

      - name: Checkout base commit
        run: git checkout ${{ github.event.pull_request.base.sha }}

      - name: Get copies of test files from the PR to base branch
        run: |
          git checkout ${{ github.event.pull_request.head.sha }} -- test/

      - name: Build base site
        run: |
          "$ZOLA_BIN" build --base-url "http://127.0.0.1:1111"

      - name: Generate base snapshots
        working-directory: test
        run: |
          npx playwright test tests/visual-regression-test.spec.ts --update-snapshots

      - name: Checkout PR head
        run: git checkout ${{ github.event.pull_request.head.sha }}

      - name: Build PR site
        run: |
          "$ZOLA_BIN" build --base-url "http://127.0.0.1:1111"

      - name: Run visual regression test
        working-directory: test
        run: npx playwright test tests/visual-regression-test.spec.ts
        continue-on-error: true
        id: vrt-test

      - name: Upload VRT results
        uses: actions/upload-artifact@v4
        with:
          path: |
            test/test-results/
            test/playwright-report/
          retention-days: 30

  comment:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.pull_request.head.repo.fork == false
    steps:
      - name: Comment VRT result
        uses: actions/github-script@v7
        with:
          script: |
            const status = "${{ needs.test.outputs.vrt_failed }}" === "true"
              ? "⚠️ **VRT detected visual changes**"
              : "✅ **VRT passed with no visual differences**"
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `${status}\n\nDownload the CI artifact to view details.`
            })
